/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_eduardoaguilar;

import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author eagui
 */
public class Frame extends javax.swing.JFrame {

    ArrayList<Clases> lista_c = new ArrayList();
    ArrayList<Clases> container = new ArrayList();
    ArrayList<String> atributos = new ArrayList();
    ArrayList<String> methods = new ArrayList();
    ArrayList<String> classes = new ArrayList();
    ArrayList<Flujos> contenidos = new ArrayList();
    ArrayList<Flujos> container2 = new ArrayList();
    ArrayList<String> variables = new ArrayList();
    ArrayList<String> variables2 = new ArrayList();
    public Frame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Flow = new javax.swing.JDialog();
        pane1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areatext = new javax.swing.JTextArea();
        inicio = new javax.swing.JRadioButton();
        cif = new javax.swing.JRadioButton();
        cw = new javax.swing.JRadioButton();
        ceif = new javax.swing.JRadioButton();
        proc = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jt_variable1 = new javax.swing.JTextField();
        str2 = new javax.swing.JRadioButton();
        inte2 = new javax.swing.JRadioButton();
        charr2 = new javax.swing.JRadioButton();
        lonng2 = new javax.swing.JRadioButton();
        bool2 = new javax.swing.JRadioButton();
        dd2 = new javax.swing.JRadioButton();
        shortt2 = new javax.swing.JRadioButton();
        floaat2 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        variab = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        UML1 = new javax.swing.JDialog();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jt_class = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt_method = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_variable = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        str = new javax.swing.JRadioButton();
        inte = new javax.swing.JRadioButton();
        charr = new javax.swing.JRadioButton();
        lonng = new javax.swing.JRadioButton();
        bool = new javax.swing.JRadioButton();
        dd = new javax.swing.JRadioButton();
        shortt = new javax.swing.JRadioButton();
        floaat = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        pub = new javax.swing.JRadioButton();
        priv = new javax.swing.JRadioButton();
        inte1 = new javax.swing.JRadioButton();
        str1 = new javax.swing.JRadioButton();
        charr1 = new javax.swing.JRadioButton();
        lonng1 = new javax.swing.JRadioButton();
        bool1 = new javax.swing.JRadioButton();
        dd1 = new javax.swing.JRadioButton();
        shortt1 = new javax.swing.JRadioButton();
        floaat1 = new javax.swing.JRadioButton();
        jButton13 = new javax.swing.JButton();
        pane2 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        CODE = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        code_here = new javax.swing.JTextArea();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pane = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        pane1.setBackground(new java.awt.Color(255, 255, 255));
        pane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pane1Layout = new javax.swing.GroupLayout(pane1);
        pane1.setLayout(pane1Layout);
        pane1Layout.setHorizontalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
        );
        pane1Layout.setVerticalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton5.setText("Agregar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton10.setText("Save");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        areatext.setColumns(20);
        areatext.setRows(5);
        jScrollPane3.setViewportView(areatext);

        buttonGroup4.add(inicio);
        inicio.setText("Inicio/Fin");

        buttonGroup4.add(cif);
        cif.setText("Ciclo If");

        buttonGroup4.add(cw);
        cw.setText("Ciclo While");

        buttonGroup4.add(ceif);
        ceif.setText("Ciclo Else If");

        buttonGroup4.add(proc);
        proc.setText("Proceso");

        jLabel5.setText("Atributos:");

        jt_variable1.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup5.add(str2);
        str2.setText("String");

        buttonGroup5.add(inte2);
        inte2.setText("Integer");

        buttonGroup5.add(charr2);
        charr2.setText("Character");

        buttonGroup5.add(lonng2);
        lonng2.setText("Long");

        buttonGroup5.add(bool2);
        bool2.setText("Boolean");

        buttonGroup5.add(dd2);
        dd2.setText("Double");

        buttonGroup5.add(shortt2);
        shortt2.setText("Short");

        buttonGroup5.add(floaat2);
        floaat2.setText("Float");

        jButton7.setText("Agregar Atributo");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        buttonGroup4.add(variab);
        variab.setText("Variables");

        jButton4.setText("Generar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton8.setText("PDF");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton16.setText("PNG");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });

        jMenu5.setText("Menu");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Inicio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Abrir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar4.add(jMenu5);

        Flow.setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout FlowLayout = new javax.swing.GroupLayout(Flow.getContentPane());
        Flow.getContentPane().setLayout(FlowLayout);
        FlowLayout.setHorizontalGroup(
            FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FlowLayout.createSequentialGroup()
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FlowLayout.createSequentialGroup()
                                .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inicio)
                                    .addComponent(cif, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FlowLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(cw, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(FlowLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ceif, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FlowLayout.createSequentialGroup()
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FlowLayout.createSequentialGroup()
                                .addComponent(proc, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(variab, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FlowLayout.createSequentialGroup()
                                .addComponent(charr2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lonng2))
                            .addGroup(FlowLayout.createSequentialGroup()
                                .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(str2))
                                .addGap(25, 25, 25)
                                .addComponent(inte2))
                            .addGroup(FlowLayout.createSequentialGroup()
                                .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bool2)
                                    .addComponent(shortt2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(floaat2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FlowLayout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jt_variable1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FlowLayout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton16)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        FlowLayout.setVerticalGroup(
            FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton16))
                .addGap(15, 15, 15)
                .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FlowLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inicio)
                            .addComponent(cw))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cif)
                            .addComponent(ceif))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proc)
                            .addComponent(variab))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_variable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(str2)
                            .addComponent(inte2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(charr2)
                            .addComponent(lonng2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bool2)
                            .addComponent(dd2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FlowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shortt2)
                            .addComponent(floaat2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)))
                .addContainerGap())
        );

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jButton6.setText("Agregar Atributo");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton9.setText("Save");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel1.setText("Clase:");

        jt_class.setBackground(new java.awt.Color(255, 255, 255));
        jt_class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_classMouseClicked(evt);
            }
        });

        jLabel2.setText("Metodos:");

        jt_method.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Atributos:");

        jt_variable.setBackground(new java.awt.Color(255, 255, 255));

        jButton11.setText("Agregar ");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Agregar Metodo");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        buttonGroup1.add(str);
        str.setText("String");

        buttonGroup1.add(inte);
        inte.setText("Integer");

        buttonGroup1.add(charr);
        charr.setText("Character");

        buttonGroup1.add(lonng);
        lonng.setText("Long");

        buttonGroup1.add(bool);
        bool.setText("Boolean");

        buttonGroup1.add(dd);
        dd.setText("Double");

        buttonGroup1.add(shortt);
        shortt.setText("Short");

        buttonGroup1.add(floaat);
        floaat.setText("Float");

        jLabel4.setText("Extends:");

        combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxItemStateChanged(evt);
            }
        });

        buttonGroup2.add(pub);
        pub.setText("Public");

        buttonGroup2.add(priv);
        priv.setText("Private");

        buttonGroup3.add(inte1);
        inte1.setText("Integer");

        buttonGroup3.add(str1);
        str1.setText("String");

        buttonGroup3.add(charr1);
        charr1.setText("Character");

        buttonGroup3.add(lonng1);
        lonng1.setText("Long");

        buttonGroup3.add(bool1);
        bool1.setText("Boolean");

        buttonGroup3.add(dd1);
        dd1.setText("Double");

        buttonGroup3.add(shortt1);
        shortt1.setText("Short");

        buttonGroup3.add(floaat1);
        floaat1.setText("Float");

        jButton13.setText("Generar");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        pane2.setBackground(new java.awt.Color(255, 255, 255));
        pane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pane2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pane2Layout = new javax.swing.GroupLayout(pane2);
        pane2.setLayout(pane2Layout);
        pane2Layout.setHorizontalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        pane2Layout.setVerticalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jButton14.setText("PNG");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        jButton15.setText("PDF");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        jMenu4.setText("Menu");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Abrir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar3.add(jMenu4);

        UML1.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout UML1Layout = new javax.swing.GroupLayout(UML1.getContentPane());
        UML1.getContentPane().setLayout(UML1Layout);
        UML1Layout.setHorizontalGroup(
            UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UML1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jt_variable, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addComponent(jButton13)
                            .addGap(35, 35, 35)
                            .addComponent(jButton9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UML1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jt_class))
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jt_method))
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addComponent(charr1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lonng1))
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bool1)
                                .addComponent(shortt1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(floaat1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dd1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(str1)
                                .addComponent(pub))
                            .addGap(24, 24, 24)
                            .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(priv)
                                .addComponent(inte1)))
                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addComponent(charr)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lonng))
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(str))
                            .addGap(25, 25, 25)
                            .addComponent(inte))
                        .addGroup(UML1Layout.createSequentialGroup()
                            .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bool)
                                .addComponent(shortt))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dd, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(floaat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(UML1Layout.createSequentialGroup()
                        .addComponent(jButton14)
                        .addGap(18, 18, 18)
                        .addComponent(jButton15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(pane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UML1Layout.setVerticalGroup(
            UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UML1Layout.createSequentialGroup()
                .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UML1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton14)
                            .addComponent(jButton15))
                        .addGap(18, 18, 18)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jt_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jt_method, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pub)
                            .addComponent(priv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(str1)
                            .addComponent(inte1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(charr1)
                            .addComponent(lonng1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bool1)
                            .addComponent(dd1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shortt1)
                            .addComponent(floaat1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)
                        .addGap(18, 18, 18)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_variable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(str)
                            .addComponent(inte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(charr)
                            .addComponent(lonng))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bool)
                            .addComponent(dd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shortt)
                            .addComponent(floaat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UML1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton13)))
                    .addGroup(UML1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        code_here.setEditable(false);
        code_here.setColumns(20);
        code_here.setRows(5);
        jScrollPane2.setViewportView(code_here);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout CODELayout = new javax.swing.GroupLayout(CODE.getContentPane());
        CODE.getContentPane().setLayout(CODELayout);
        CODELayout.setHorizontalGroup(
            CODELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CODELayout.setVerticalGroup(
            CODELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("UML");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Flujo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        pane.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(pane);

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 496, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(56, 56, 56))
        );

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        pane.setText("");
        pane.setText("Un Diagrama de Flujo representa la esquematización gráfica de un algoritmo,\nel "
                + "cual muestra gráficamente los pasos o procesos a seguir para alcanzar la \nsolución "
                + "de un problema. Su correcta construcción es sumamente importante porque, a partir "
                + "del mismo se escribe un programa en algún Lenguaje de Programación."
        );
        flag = 1;

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        pane.setText(""
                + "El Lenguaje Unificado de Modelado (UML) fue creado para forjar un lenguaje de\nmodelado "
                + "visual común y semántica y sintácticamente rico para la arquitectura, el diseño y la "
                + "implementación de sistemas de software complejos, tanto en estructura como en comportamiento.");
        flag = 2;
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (flag == 1) {
           
            Flow.setVisible(true);
            Flow.setModal(true);
            Flow.pack();
            Flow.setLocationRelativeTo(this);
            
            this.dispose();
            pane1.setLayout(new LayOut());
            //Flow.add(pane1,BorderLayout.CENTER);
            Flow.add(pane1);
        } else if (flag == 2) {
            
            UML1.setVisible(true);
            UML1.setModal(true);
            UML1.pack();
            UML1.setLocationRelativeTo(this);
            
            this.dispose();
            
            
            pane2.setLayout(new LayOut());
            UML1.add(pane2,BorderLayout.CENTER);
            

        } else {
            JOptionPane.showMessageDialog(null, "No hay ningun diagrama seleccionado");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Metodos m = new Metodos();
        
        String content = "";
        if(inicio.isSelected()){
            verifier = 1;
            content = areatext.getText();
            Flujos f  = new Flujos(content,Color.red,variables,verifier,variables2);
            contenidos.add(f);
            pane1.add(m.crearA(content,Color.red));
            pane1.revalidate();
            validate();
            areatext.setText("");
            
        }else if(cif.isSelected()){
            verifier = 2;
            content = areatext.getText();
            Flujos f  = new Flujos(content,Color.black,variables,verifier,variables2);
            contenidos.add(f);
            pane1.add(m.crearA(content,Color.black));
            pane1.revalidate();
            validate();
            areatext.setText("");
        }else if(ceif.isSelected()){
            verifier = 3;
            content = areatext.getText();
            Flujos f  = new Flujos(content,Color.blue,variables,verifier,variables2);
            contenidos.add(f);
            pane1.add(m.crearA(content,Color.blue));
            pane1.revalidate();
            validate();
            areatext.setText("");
        }else if(cw.isSelected()){
            verifier = 4;
            content = areatext.getText();
            Flujos f  = new Flujos(content,Color.yellow,variables,verifier,variables2);
            contenidos.add(f);
            pane1.add(m.crearA(content,Color.yellow));
            pane1.revalidate();
            validate();
            areatext.setText("");
        }else if (proc.isSelected()){
            verifier = 5;
            content = areatext.getText();
            Flujos f  = new Flujos(content,Color.green,variables,verifier,variables2);
            contenidos.add(f);
            pane1.add(m.crearA(content,Color.magenta));
            pane1.revalidate();
            validate();
            areatext.setText("");
            
        }else if(variab.isSelected()){
            verifier = 6;
            Flujos f  = new Flujos(variables.toString(),Color.green,variables,verifier,variables2);
            contenidos.add(f);
            pane1.add(m.crearA(variables.toString(),Color.pink));
            pane1.revalidate();
            validate();
            areatext.setText("");
            
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane1MouseClicked
        Stroke stroke = new BasicStroke(3f);
        
        
        if (startX == -1 && startY == -1) {
            startX = evt.getX();
            startY = evt.getY();
        } else {
            Graphics g = this.pane1.getGraphics();
            Graphics2D g2d = (Graphics2D) g;
            g2d.setStroke(stroke);
            g2d.drawLine(startX, startY,
                    evt.getX(), evt.getY());
            // reset the start point
            startX = -1;
            startY = -1;
        }
    }//GEN-LAST:event_pane1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Frame f = new Frame();
        f.setVisible(true);
        f.setLocationRelativeTo(this);
        UML1.setVisible(false);
        pane2.removeAll();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        Frame f = new Frame();
        f.setVisible(true);
        f.setLocationRelativeTo(this);
        Flow.setVisible(false);
        pane1.removeAll();
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Frame f = new Frame();
        f.setVisible(true);
        f.setLocationRelativeTo(this);
        Flow.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter(
                        "Eduardo Andres", "eag" );
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {

                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals(
                        "Eduardo Andres")) {
                    fichero
                            = new File(jfc.getSelectedFile().getPath()  + ".eag");
                } else {
                    fichero = jfc.getSelectedFile();
                }

                fw = new FileOutputStream(fichero);
                bw = new ObjectOutputStream(fw);
                ArrayList<String> s = new ArrayList();

                
                Documento d = new Documento(doc, estilo,lista_c);
                bw.writeObject(d);
                bw.flush();
                JOptionPane.showMessageDialog(this,
                        "Archivo guardado exitosamente");

            } catch (Exception e) {
                e.printStackTrace();
            }

        }//fin IF
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter(
                        "Eduardo Andres", "flow" );
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {

                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals(
                        "Eduardo Andres")) {
                    fichero
                            = new File(jfc.getSelectedFile().getPath()  + ".flow");
                } else {
                    fichero = jfc.getSelectedFile();
                }

                fw = new FileOutputStream(fichero);
                bw = new ObjectOutputStream(fw);
                ArrayList<String> s = new ArrayList();

                
                Documento d = new Documento(doc, contenidos, estilo);
                bw.writeObject(d);
                bw.flush();
                JOptionPane.showMessageDialog(this,
                        "Archivo guardado exitosamente");

            } catch (Exception e) {
                e.printStackTrace();
            }

        }//fin IF
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        String s="";
        if(str.isSelected()){
           s ="string " + jt_variable.getText();
        }else if(inte.isSelected()){
            s ="int " + jt_variable.getText();
        }else if(charr.isSelected()){
            s ="char " + jt_variable.getText();
        }else if(lonng.isSelected()){
            s ="long " + jt_variable.getText();
        }else if(bool.isSelected()){
            s ="bool " + jt_variable.getText();
        }else if(dd.isSelected()){
            s ="double " + jt_variable.getText();
        }else if(shortt.isSelected()){
            s ="short " + jt_variable.getText();
        }else if(floaat.isSelected()){
            s ="float " + jt_variable.getText();
        }
        atributos.add(s);
        jt_variable.setText("");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        String s = "";
        if(pub.isSelected()){
            s = "public: ";
        }else{
            s = "private: " ;
        }
        
        if(str1.isSelected()){
           s +="string " + jt_method.getText()+"()";
        }else if(inte1.isSelected()){
            s +="int " + jt_method.getText()+"()";
        }else if(charr1.isSelected()){
            s +="char " + jt_method.getText()+"()";
        }else if(lonng1.isSelected()){
            s +="long " + jt_method.getText()+"()";
        }else if(bool1.isSelected()){
            s +="bool " + jt_method.getText()+"()";
        }else if(dd1.isSelected()){
            s +="double " + jt_method.getText()+"()";
        }else if(shortt1.isSelected()){
            s +="short " + jt_method.getText()+"()";
        }else if(floaat1.isSelected()){
            s +="float " + jt_method.getText()+"()";
        }
        
        methods.add(s);
        jt_method.setText("");
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
      
        if(!flag1){
            String clase = jt_class.getText();
            classes.add(clase);
            jt_class.setText("");
            combobox.addItem(clase);
            Metodos m = new Metodos();
            pane2.add(m.creart(clase, methods, atributos));
            pane2.revalidate();
            validate();

            Clases c = new Clases(clase);
            for (int i = 0; i < atributos.size(); i++) {
                c.setY(atributos.get(i));
            }
            for (int i = 0; i < methods.size(); i++) {
                c.setX(methods.get(i));
            }
            lista_c.add(c);
            
            methods.clear();
            atributos.clear();

            flag1 = false;
            try {
                combobox.setSelectedIndex(-1);
            } catch (NullPointerException e) {

            }
        }else{
            String clase = jt_class.getText();
            classes.add(clase);
            jt_class.setText("");
            combobox.addItem(clase);
            Metodos m = new Metodos();
            pane2.add(m.creart(clase, methods, atributos));
            pane2.revalidate();
            validate();

            Clases c = new Clases(clase);
            for (int i = 0; i < atributos.size(); i++) {
                c.setY(atributos.get(i));
            }
            for (int i = 0; i < methods.size(); i++) {
                c.setX(methods.get(i));
            }
            c.setExtend(extend);
            lista_c.add(c);
            methods.clear();
            atributos.clear();

            flag1 = false;
            try {
                combobox.setSelectedIndex(-1);
            } catch (NullPointerException e) {

            }
        }
        
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void comboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxItemStateChanged
        flag1 = true;
        try{
            Object selected = combobox.getSelectedItem();
            extend = selected.toString();
        }catch(NullPointerException e){
            
        }
        
    }//GEN-LAST:event_comboboxItemStateChanged

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        CODE.setVisible(true);
        CODE.setModal(true);
        CODE.pack();
        CODE.setLocationRelativeTo(this);
        Metodos m = new Metodos();
        code_here.setText(m.GenCode(code_here, lista_c));
       
    }//GEN-LAST:event_jButton13MouseClicked

    private void jt_classMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_classMouseClicked
        
    }//GEN-LAST:event_jt_classMouseClicked

    private void pane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pane2MouseClicked
        Stroke stroke = new BasicStroke(3f);
        
        if (startX == -1 && startY == -1) {
            startX = evt.getX();
            startY = evt.getY();
        } else {
            Graphics g = this.pane2.getGraphics();
            Graphics2D g2d = (Graphics2D) g;
            g2d.setStroke(stroke);
            g2d.drawLine(startX, startY,
                    evt.getX(), evt.getY());
            // reset the start point
            startX = -1;
            startY = -1;
        }
    }//GEN-LAST:event_pane2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Metodos m = new Metodos();
        File fichero = null;
        FileInputStream entrada = null;
        ObjectInputStream objeto = null;        
        try {
            JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter filtro = 
                    new FileNameExtensionFilter(
                            "Eduardo Andres","eag");
            jfc.setFileFilter(filtro);                   
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION)
            {
               fichero = jfc.getSelectedFile();
                entrada
                    = new FileInputStream(fichero);
                 objeto
                    = new ObjectInputStream(entrada);              
               
               Documento temp=(Documento)objeto.readObject();
               container = ( ((Documento)  temp  ).getX() );
               for(int i = 0 ; i<container.size() ; i++){
                   String name = container.get(i).getName();
                   ArrayList<String> met = container.get(i).getX();
                   ArrayList<String> at = container.get(i).getY();
                   pane2.add(m.creart(name, met, at));
                   pane2.revalidate();
                   validate();
                   
               }
               
            } //fin if
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            objeto.close();
            entrada.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Metodos m = new Metodos();
        File fichero = null;
        FileInputStream entrada = null;
        ObjectInputStream objeto = null;
        try {
            JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter filtro
                    = new FileNameExtensionFilter(
                            "Eduardo Andres", "flow");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                entrada
                        = new FileInputStream(fichero);
                objeto
                        = new ObjectInputStream(entrada);

                Documento temp = (Documento) objeto.readObject();
                container2 = (((Documento) temp).getY());
                for (int i = 0; i < container2.size(); i++) {
                    String contents = container2.get(i).getContent();
                    Color c = container2.get(i).getC();
                    pane1.add(m.crearA(contents, c));
                    pane1.revalidate();
                    validate();
                }

            } //fin if

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            objeto.close();
            entrada.close();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        String s="";
        String m = "";
        if(str2.isSelected()){
           s ="string " + jt_variable1.getText();
           m = jt_variable1.getText();
        }else if(inte2.isSelected()){
            s ="int " + jt_variable1.getText();
            m = jt_variable1.getText();
        }else if(charr2.isSelected()){
            s ="char " + jt_variable1.getText();
            m = jt_variable1.getText();
        }else if(lonng2.isSelected()){
            s ="long " + jt_variable1.getText();
            m = jt_variable1.getText();
        }else if(bool2.isSelected()){
            s ="bool " + jt_variable1.getText();
            m = jt_variable1.getText();
        }else if(dd2.isSelected()){
            s ="double " + jt_variable1.getText();
            m = jt_variable1.getText();
        }else if(shortt2.isSelected()){
            s ="short " + jt_variable1.getText();
            m = jt_variable1.getText();
        }else if(floaat2.isSelected()){
            s ="float " + jt_variable1.getText();
            m = jt_variable1.getText();
        }
        variables2.add(m);
        variables.add(s);
        
        jt_variable1.setText("");
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        CODE.setVisible(true);
        CODE.setModal(true);
        CODE.pack();
        CODE.setLocationRelativeTo(this);
        Metodos m = new Metodos();
        code_here.setText(m.GenCode2(code_here, contenidos));
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        Metodos m = new Metodos();
        String s = JOptionPane.showInputDialog("Nombre de Archivo");
        m.guardar3(pane1, s);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        Metodos m = new Metodos();
        String s = JOptionPane.showInputDialog("Nombre de Archivo");
        m.saveImage(pane2, s);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        Metodos m = new Metodos();
        String s = JOptionPane.showInputDialog("Nombre de Archivo");
        m.guardar3(pane2, s);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        Metodos m = new Metodos();
        String s = JOptionPane.showInputDialog("Nombre de Archivo");
        m.saveImage(pane1, s);
    }//GEN-LAST:event_jButton16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);new Frame().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CODE;
    private javax.swing.JDialog Flow;
    private javax.swing.JDialog UML1;
    private javax.swing.JTextArea areatext;
    private javax.swing.JRadioButton bool;
    private javax.swing.JRadioButton bool1;
    private javax.swing.JRadioButton bool2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton ceif;
    private javax.swing.JRadioButton charr;
    private javax.swing.JRadioButton charr1;
    private javax.swing.JRadioButton charr2;
    private javax.swing.JRadioButton cif;
    private javax.swing.JTextArea code_here;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JRadioButton cw;
    private javax.swing.JRadioButton dd;
    private javax.swing.JRadioButton dd1;
    private javax.swing.JRadioButton dd2;
    private javax.swing.JRadioButton floaat;
    private javax.swing.JRadioButton floaat1;
    private javax.swing.JRadioButton floaat2;
    private javax.swing.JRadioButton inicio;
    private javax.swing.JRadioButton inte;
    private javax.swing.JRadioButton inte1;
    private javax.swing.JRadioButton inte2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jt_class;
    private javax.swing.JTextField jt_method;
    private javax.swing.JTextField jt_variable;
    private javax.swing.JTextField jt_variable1;
    private javax.swing.JRadioButton lonng;
    private javax.swing.JRadioButton lonng1;
    private javax.swing.JRadioButton lonng2;
    private javax.swing.JTextPane pane;
    private javax.swing.JPanel pane1;
    private javax.swing.JPanel pane2;
    private javax.swing.JRadioButton priv;
    private javax.swing.JRadioButton proc;
    private javax.swing.JRadioButton pub;
    private javax.swing.JRadioButton shortt;
    private javax.swing.JRadioButton shortt1;
    private javax.swing.JRadioButton shortt2;
    private javax.swing.JRadioButton str;
    private javax.swing.JRadioButton str1;
    private javax.swing.JRadioButton str2;
    private javax.swing.JRadioButton variab;
    // End of variables declaration//GEN-END:variables
    StyledDocument doc;
    Style estilo;
    
    int flag = 0;
    private int startX = -1;
    private int startY = -1;
    
    boolean flag1=false;
    String extend="";
    int verifier = 0;
}
